// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_world.proto

package com.grpc.example;

public final class CreateUser {
  private CreateUser() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_example_UserRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_grpc_example_UserRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_grpc_example_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_grpc_example_UserResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021hello_world.proto\022\020com.grpc.example\"(\n" +
      "\013UserRequest\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\t\"" +
      "\032\n\014UserResponse\022\n\n\002id\030\001 \001(\t2b\n\021CreateUse" +
      "rService\022M\n\nCreateUser\022\035.com.grpc.exampl" +
      "e.UserRequest\032\036.com.grpc.example.UserRes" +
      "ponse\"\000B#\n\020com.grpc.exampleB\nCreateUserP" +
      "\001\210\001\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_grpc_example_UserRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_grpc_example_UserRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_grpc_example_UserRequest_descriptor,
        new java.lang.String[] { "Name", "Age", });
    internal_static_com_grpc_example_UserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_grpc_example_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_grpc_example_UserResponse_descriptor,
        new java.lang.String[] { "Id", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
