// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_world.proto

package com.grpc.example;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.example.UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>optional string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
