// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_world.proto

package com.grpc.example;

public interface UserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.grpc.example.UserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional string age = 2;</code>
   */
  java.lang.String getAge();
  /**
   * <code>optional string age = 2;</code>
   */
  com.google.protobuf.ByteString
      getAgeBytes();
}
